- name: install redis server
  apt:
    name: redis-server
    state: present
    update_cache: yes

- name: update mongodb conf file
  replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: 0.0.0.0

- name: restart redis
  systemd:
    name: redis
    enabled: yes
    state: restarted