- name: Add Mongodb key
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-4.4.asc
    state: present

- name: Add mongodb repository
  apt_repository:
    repo: deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse
    state: present

- name: update cache
  apt:
    update_cache: yes

- name: install mongodb
  apt:
    name: mongodb-org
    state: present

- name: update mongodb conf file
  replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: 0.0.0.0

- name: Make sure a service unit is running
  systemd:
    state: started
    name: mongod
    enabled: yes


- name: Download schema
  unarchive:
    src: https://github.com/GDevOps321/mongodb/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: load schema
  shell: mongo < /tmp/mongodb-main/{{ item }}.js
  loop:
     - users
     - catalogue