- name: demo on filters
  hosts: all
  vars:
    url: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html
  tasks:
    - name: split the link
      debug:
        msg: url = {{ url | urlsplit }}