- name: frontend
  hosts: all
  become: yes
  roles:
    - role: frontend
      tags: frontend
      when: COMPONENT == "frontend"

- name: mongodb
  hosts: all
  become: yes
  roles:
    - role: mongodb
      tags: mongodb
      when: COMPONENT == "mongodb"

