- name: sample
  hosts: all
  vars_files:
    - example.yml
  vars_prompt:
    - name: url
      prompt: ENTER url
      private: no
  vars:
    url: frooty.com
  tasks:
    - name: variables
      debug:
        msg: url = {{ url }}
    - name: local variable
      debug:
        msg:
          url = {{ url }}
      vars:
        url: avk.com
# command line -e URL=example
# tasks
# vars_file
# vars_prompt
# vars
# inv

    - name: sample 2
      debug:
        msg: hostname ={{ ansible_hostname }}