- name: sample
  hosts: all
  vars:
    url: frooty.com
  tasks:
    - name: variables
      debug:
        msg: url = {{ url }}
    - name: local variable
      debug:
        msg:
          SMP = {{ SMP }}
      vars:
        SMP: avk.com