- name: npm install
  apt:
    name: npm
    state: present
    update_cache: yes

- name: Add the user
  user:
    name: roboshop
    shell: /bin/bash

- name: Download file
  get_url:
    url: http://172.31.20.130:8081/repository/user/user-main.zip
    dest: /tmp/user-main.zip
    username: admin
    password: admin

- name: delete the content
  file:
    path: /home/roboshop/user
    state: absent

- name: create a dicrectory
  file:
    path: /home/roboshop/user
    state: directory
    #switch to user
    owner: roboshop
    group: roboshop

- name: Extract file
  unarchive:
    src: /tmp/user-main.zip
    dest: /home/roboshop/user
    remote_src: yes
    owner: roboshop
    group: roboshop

- name: copy user service
  copy:
    src: user.service
    dest: /etc/systemd/system/user.service

- name: restart user
  systemd:
    name: user
    state: started
    daemon-reload: yes
    enabled: yes




