- name: install docker
  shell : curl -s get.docker.com | bash

- name: start docker
  systemd:
    name: docker
    state: started
    enabled: yes

- name: create the directory
  file:
    path: /data
    state: directory

- name: create a mysql container
  docker_container:
    name: mysql
    image: mysql:5.7.33
    volumes:
      - "/data:/var/lib/mysql"
    ports:
      - "3306:3306"
    env:
      - MYSQL_ROOT_PASSWORD: "password"
