- name: check the status of the docker
  shell: systemctl status docker
  register: out

- name: install docker
  shell : curl -s get.docker.com | bash
  when: out.rc !=0

- name: start docker
  systemd:
    name: docker
    state: started
    enabled: yes

- name: install python
  apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: install pip3 docker module
  pip:
    name: docker
    executable: pip3

- name: create the directory
  file:
    path: /data
    state: directory

- name: create a mysql container
  docker_container:
    name: mysql
    image: mysql:5.7.33
    volumes:
      - "/data:/var/lib/mysql"
    ports:
      - "3306:3306"
    env:
      - MYSQL_ROOT_PASSWORD: "password"

- name: Download schema
  unarchive:
    src: https://github.com/GDevOps321/mysql/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: install mysql client
  apt:
    name: mysql-client-core-8.0
    state: present

- name: load schema
  mysql_db:
    name: all
    state: import
    target: /tmp/mysql-main/shipping.sql
    login_host: "{{ ansible_default_ipv4.adress}}"
    login_user: root
    login_password: password




