- name: npm install
  apt:
    name: npm
    state: present
    update_cache: yes

- name: Add the user
  user:
    name: roboshop
    shell: /bin/bash

- name: Download file
  get_url:
    url: http://172.31.20.130:8081/repository/catalogue/catalogue-main.zip
    dest: /tmp/catalogue-main.zip
    username: admin
    password: admin

- name: delete the content
  file:
    path: /home/roboshop/catalogue
    state: absent

- name: create a dicrectory
  file:
    path: /home/roboshop/catalogue
    state: directory
    #switch to user
    owner: roboshop
    group: roboshop

- name: Extract file
  unarchive:
    src: /tmp/catalogue-main.zip
    dest: /home/roboshop/catalogue
    remote_src: yes

- name: copy catalogue service
  copy:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service

- name: restart catalogue
  systemd:
    name: catalogue
    state: started
    daemon-reload: yes
    enabled: yes




