- name: npm install
  apt:
    name: npm
    state: present
    update_cache: yes

- name: download artifacts from nexus
  include_tasks: download_nexus.yml


- name: download artifacts from nexus
  include_tasks: services.yml




