- name: install maven
  apt:
    name: maven
    state: present
    update_cache: yes

- name: download artifacts from nexus
  include_tasks: download_nexus.yml

- name: download artifacts from nexus
  include_tasks: download_nexus.yml
