- name: npm install
  apt:
    name: npm
    state: present
    update_cache: yes

- name: Add the user
  user:
    name: roboshop
    shell: /bin/bash

- name: Download file
  get_url:
    url: http://172.31.20.130:8081/repository/cart/cart-main.zip
    dest: /tmp/cart-main.zip
    username: admin
    password: admin

- name: delete the content
  file:
    path: /home/roboshop/cart
    state: absent

- name: create a dicrectory
  file:
    path: /home/roboshop/cart
    state: directory
    #switch to user
    owner: roboshop
    group: roboshop

- name: Extract file
  unarchive:
    src: /tmp/cart-main.zip
    dest: /home/roboshop/cart
    remote_src: yes
    owner: roboshop
    group: roboshop


- name: copy cart service
  copy:
    src: cart.service
    dest: /etc/systemd/system/cart.service

- name: restart cart
  systemd:
    name: cart
    state: started
    daemon-reload: yes
    enabled: yes




